### ISSUE TITLE
dead link to blog post

### ISSUE THREAD

**Issue by kyle-marshall** [Wuelle/Leuchtkraft#1]
Hello, I enjoyed pondering over the bird example, but the [link to your blog post](https://wuelle.dev/blog/posts/leuchtkraft/) in the README is not currently working. I was excited to read it, weil es eine grossartige Idee ist!

**Comment by simonwuelker** [comment]
Thanks - the website has been down for a while (might put it up again soon), I should probably remove the link in the readme.
In the meantime, you can read the archive.org version: https://web.archive.org/web/20220703170101/https://wuelle.dev/blog/posts/leuchtkraft/
Now that i think about it, I might link this version in the readme...
